name = "demo-agent"
account_id = "94f7b77cd26282ff403a39158234ee08"
workers_dev = false
compatibility_date = "2024-09-23"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

[env.dev]
ENVIRONMENT = "dev"

[[env.dev.kv_namespaces]]
binding = "LINEAR_TOKENS"
id = "65c60031d7784c42b683000148587c0f"

[env.production]
ENVIRONMENT = "production"

[[env.production.kv_namespaces]]
binding = "LINEAR_TOKENS"
id = "d3b2aedc00764330b0859837a7f4676b"

